# Generated by Django 6.0.4 on 2026-04-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0005_remove_discount_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("currency", models.CharField(max_length=3, unique=True)),
                ("rate", models.DecimalField(decimal_places=8, max_digits=18)),
                ("fetched_at", models.DateTimeField()),
            ],
            options={
                "db_table": "exchange_rates",
            },
        ),
    ]
