# Generated by Django 6.0.4 on 2026-04-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_drop_free_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancel_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
