# Generated by Django 6.0.4 on 2026-05-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_subscription_cancel_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='scheduled_change_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='scheduled_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_subscriptions', to='billing.plan'),
        ),
    ]
