# Generated by Django 6.0.4 on 2026-05-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_subscription_scheduled_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='quantity',
            new_name='seat_limit',
        ),
    ]
