# Generated by Django 6.0.4 on 2026-04-30 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_performance_audit_indexes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="account_type",
        ),
    ]
