# Generated by Django 6.0.5 on 2026-05-06 14:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinkRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(max_length=20)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_link_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_link_requests',
                'abstract': False,
            },
        ),
    ]
