# Generated by Django 6.0.5 on 2026-05-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_sociallinkrequest'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sociallinkrequest',
            index=models.Index(fields=['expires_at'], name='idx_social_link_expires_at'),
        ),
    ]
