# Generated by Django 6.0.5 on 2026-05-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_sociallinkrequest_expires_at_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['expires_at'], name='idx_email_verif_expires_at'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['expires_at'], name='idx_pwd_reset_expires_at'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['expires_at'], name='idx_refresh_expires_at'),
        ),
        migrations.AddIndex(
            model_name='sociallinkrequest',
            index=models.Index(condition=models.Q(('used_at__isnull', True)), fields=['user'], name='idx_social_link_user_active'),
        ),
    ]
