# Generated by Django 6.0.4 on 2026-04-28 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0010_remove_org_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="orgmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "owner")),
                fields=("user",),
                name="uniq_org_owner_per_user",
            ),
        ),
    ]
