# Generated by Django 6.0.5 on 2026-05-07 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0011_uniq_org_owner_per_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Heal any pre-existing rows that violate the new invariant before
        # adding the constraint — owner rows that slipped through with
        # ``is_billing=False`` (legacy data, manual admin edits, prior
        # migrations) would otherwise reject the AddConstraint.
        migrations.RunSQL(
            sql=(
                "UPDATE org_members SET is_billing = TRUE"
                " WHERE role = 'owner' AND is_billing = FALSE;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddConstraint(
            model_name="orgmember",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_billing", True), ("role", "owner")),
                    models.Q(("role", "owner"), _negated=True),
                    _connector="OR",
                ),
                name="ck_org_owner_must_be_billing",
            ),
        ),
    ]
