# Generated by Django 6.0.5 on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0013_alter_org_slug_field_unique"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="orgmember",
            index=models.Index(fields=["user"], name="idx_orgmember_user"),
        ),
    ]
